# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: vunguye1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: ghcr.io/shuguet/pacman:latest
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: pacman-config
          resources:
            requests:
              cpu: 10m
              memory: 12Mi
            limits:
              memory: 24Mi