# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048
  namespace: vunguye1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 2048
  template:
    metadata:
      labels:
        app: 2048
    spec:
      containers:
        - name: 2048
          image: ghcr.io/daocloud/dao-2048:v1.4.1
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: 2048-config
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 240Mi