# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idk
  namespace: vunguye1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: idk
  template:
    metadata:
      labels:
        app: idk
    spec:
      containers:
        - name: idk
          image: pengbai/docker-supermario
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: whoami-config
          resources:
            requests:
              cpu: 10m
              memory: 12Mi
            limits:
              memory: 1Gi