# http-route.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: flappybird
  namespace: vunguye1
spec:
  parentRefs:
    - name: gke-gateway
      namespace: gateway
  hostnames:
    - flappybird-vunguye1.s9n.no
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: flappybird
          port: 80