# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: 2048
  namespace: vunguye1
spec:
  type: ClusterIP
  selector:
    app: 2048
  ports:
    - name: web
      port: 80
      targetPort: http