# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flappybird
  namespace: vunguye1
spec:
  type: ClusterIP
  selector:
    app: flappybird
  ports:
    - name: web
      port: 80
      targetPort: http